export * from './registry';
export * from './lib/text';
export * from './lib/encoding';
export * from './lib/json';
export * from './lib/csv';
export * from './lib/units';
export * from './lib/color';
export * from './lib/time';
export * from './lib/random';
export * from './lib/hash';
export * from './lib/qr';
export * from './lib/markdown';
export * from './lib/format';
export * from './lib/calc/expression';
export * from './lib/calc/money';
export * from './lib/calc/finance';
export * from './lib/calc/everyday';
export * from './lib/calc/specs';

export const APP_NAME = 'OmniKit';
export const APP_TAGLINE = 'Everyday file, text and developer tools that run entirely on your device.';
